name: dubii-python
# channels priority
# see https://bioconda.github.io/
# conda-forge has highest prioriy
channels:
    - defaults
    - bioconda
    - conda-forge
dependencies:
    - python=3.7
    - jupyterlab=2
    - ipywidgets
    - numpy
    - scipy
    - pandas
    - pandas-profiling
    - xlrd # to read .xls files with Pandas
    - openpyxl # to read .xlsx files with Pandas
    - matplotlib
    - seaborn
    - bokeh
    - plotly
    - biopython
    - scikit-learn
    - scikit-bio
    - nodejs
    - pip
    - pip:
        - watermark
        - bcbio-gff
